stages:
  - test
  - deploy

test-pages:
  stage: test
  image: minidocks/mkdocs
  script:
    - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
      - test
  except:
    - main

deploy-pages:
  stage: deploy
  image: minidocks/mkdocs
  script:
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  only:
    - main
