stages:
  - build
  - deploy

build-pages:
  stage: build
  image:
    name: squidfunk/mkdocs-material
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdocs build
  artifacts:
    untracked: true
    expire_in: 1 hour
  only:
    - main

deploy-pages:
  dependencies:
    - build-pages
  stage: deploy
  image: minidocks/mkdocs
  before_script:
    - apk update
    - apk add --no-cache git
    - git clone https://${MKDOCKS_ACCES_TOKEN_NAME}:${MKDOCS_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git "${CI_COMMIT_SHA}"
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"

  script:
    - cd "${CI_COMMIT_SHA}"
    - mkdocs gh-deploy
  only:
    - main
